name: Keep Backend Alive

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Curl backend
        run: curl -m 10 https://Ripple-Realtime-Chat-App.onrender.com/health || true
